export interface ElectionSymbol {
  id: string;
  name: string;
  iconName: string;
}

export const ELECTION_SYMBOLS: ElectionSymbol[] = [
  { id: "173", name: "Leaf", iconName: "nature" },
  { id: "289", name: "Camera", iconName: "photo_camera" },
  { id: "294", name: "Sun", iconName: "light_mode" },
  { id: "316", name: "Apple", iconName: "apple" },
  { id: "326", name: "Book", iconName: "menu_book" },
  { id: "345", name: "Chair", iconName: "chair" },
  { id: "354", name: "Mouse", iconName: "mouse" },
  { id: "376", name: "Stethoscope", iconName: "medical_services" },
  { id: "382", name: "Football", iconName: "sports_soccer" },
  { id: "390", name: "Bus", iconName: "directions_bus" },
  { id: "394", name: "Laptop", iconName: "laptop" },
  { id: "404", name: "Star", iconName: "star" },
  { id: "418", name: "Jeep", iconName: "local_taxi" },
  { id: "435", name: "Tree", iconName: "forest" },
  { id: "502", name: "Cup", iconName: "coffee" },
  { id: "511", name: "Phone", iconName: "phone_enabled" },
  { id: "524", name: "Pen", iconName: "edit" },
  { id: "542", name: "Fan", iconName: "mode_fan" },
  { id: "550", name: "Aeroplane", iconName: "flight" },
  { id: "559", name: "Bicycle", iconName: "pedal_bike" },
  { id: "561", name: "Balloon", iconName: "celebration" },
  { id: "564", name: "Guitar", iconName: "music_note" },
  { id: "568", name: "Umbrella", iconName: "beach_access" },
  { id: "576", name: "Clock", iconName: "schedule" },
  { id: "577", name: "Cap", iconName: "architecture" },
  { id: "582", name: "Lock", iconName: "lock" },
  { id: "588", name: "Spectacles", iconName: "visibility" },
  { id: "597", name: "House", iconName: "home" },
  { id: "598", name: "Racket", iconName: "sports_tennis" },
  { id: "604", name: "Car", iconName: "directions_car" },
  { id: "612", name: "Chessboard", iconName: "grid_view" },
  { id: "613", name: "Bird", iconName: "flight_takeoff" },
  { id: "624", name: "Cricket Bat", iconName: "sports_cricket" },
  { id: "625", name: "Scooter", iconName: "electric_scooter" },
  { id: "629", name: "Scale", iconName: "balance" },
  { id: "633", name: "Kite", iconName: "navigation" },
  { id: "635", name: "Boat", iconName: "directions_boat" },
  { id: "637", name: "Butterfly", iconName: "all_inclusive" },
  { id: "638", name: "Bell", iconName: "notifications_active" },
  { id: "10", name: "Rocket", iconName: "rocket" },
  { id: "11", name: "Anchor", iconName: "anchor" },
  { id: "12", name: "Flag", iconName: "flag" },
  { id: "13", name: "Map", iconName: "map" },
  { id: "14", name: "Globe", iconName: "public" },
  { id: "15", name: "Zap", iconName: "bolt" },
  { id: "16", name: "Water", iconName: "water_drop" },
  { id: "17", name: "Flame", iconName: "local_fire_department" },
  { id: "18", name: "Flower", iconName: "local_florist" },
  { id: "19", name: "Gift", iconName: "card_giftcard" },
  { id: "20", name: "Shopping Bag", iconName: "shopping_bag" },
  { id: "21", name: "Briefcase", iconName: "work" },
  { id: "22", name: "Trophy", iconName: "emoji_events" },
  { id: "23", name: "Shield", iconName: "shield" },
  { id: "24", name: "Sword", iconName: "gavel" },
  { id: "25", name: "Wrench", iconName: "build" },
  { id: "26", name: "Hammer", iconName: "construction" },
  { id: "27", name: "Scissors", iconName: "content_cut" },
  { id: "28", name: "Microscope", iconName: "biotech" },
  { id: "29", name: "Calculator", iconName: "calculate" },
  { id: "30", name: "Smartphone", iconName: "smartphone" },
  { id: "31", name: "Music Note", iconName: "music_note" },
  { id: "32", name: "Mic", iconName: "mic" },
  { id: "33", name: "Headphones", iconName: "headphones" },
  { id: "34", name: "Battery", iconName: "battery_full" },
  { id: "35", name: "Wifi", iconName: "wifi" },
  { id: "36", name: "Bluetooth", iconName: "bluetooth" },
  { id: "37", name: "Search", iconName: "search" },
  { id: "38", name: "Settings", iconName: "settings" },
  { id: "39", name: "Person", iconName: "person" },
  { id: "40", name: "Groups", iconName: "groups" },
  { id: "41", name: "Email", iconName: "email" },
  { id: "42", name: "Chat", iconName: "chat" },
  { id: "43", name: "Delete", iconName: "delete" },
  { id: "44", name: "Check", iconName: "check" },
  { id: "45", name: "Arrow Up", iconName: "arrow_upward" },
  { id: "46", name: "Arrow Down", iconName: "arrow_downward" },
  { id: "47", name: "Arrow Left", iconName: "arrow_back" },
  { id: "48", name: "Arrow Right", iconName: "arrow_forward" },
  { id: "49", name: "Play", iconName: "play_arrow" },
  { id: "50", name: "Piano", iconName: "piano" },
  { id: "51", name: "Handshake", iconName: "handshake" },
  { id: "52", name: "Diamond", iconName: "diamond" },
  { id: "53", name: "Thumb Up", iconName: "thumb_up" },
  { id: "54", name: "Lightbulb", iconName: "lightbulb" },
  { id: "55", name: "Bolt", iconName: "bolt" },
  { id: "56", name: "Cloud", iconName: "cloud" },
  { id: "57", name: "Snowflake", iconName: "ac_unit" },
  { id: "58", name: "Water", iconName: "water_drop" },
  { id: "59", name: "Fire", iconName: "local_fire_department" },
  { id: "60", name: "Forest", iconName: "forest" },
  { id: "61", name: "House", iconName: "house" },
  { id: "62", name: "Store", iconName: "store" },
  { id: "63", name: "School", iconName: "school" },
  { id: "64", name: "Science", iconName: "science" },
  { id: "65", name: "Sports", iconName: "sports_basketball" },
  { id: "66", name: "Fastfood", iconName: "fastfood" },
  { id: "67", name: "Cake", iconName: "cake" },
  { id: "68", name: "Beach", iconName: "beach_access" },
  { id: "69", name: "Bed", iconName: "bed" },
  { id: "70", name: "Pool", iconName: "pool" },
];
